blank_issues_enabled: true

contact_links:
  - name: Questions
    url: https://github.com/InternLM/lmdeploy/discussions
    about: Ask questions and discuss with the LMDeploy community
  - name: Chat on Slack
    url: https://github.com/InternLM/lmdeploy
    about: Open a GitHub discussion
